---
 alice_data_folder: "/home/david/Desktop/t/data/Alice"
 bob_data_folder: "/home/david/Desktop/t/data/Bob"
 path_to_this_repo: "/home/david/Desktop/t"
 n_epochs: 10
 folds: 5
 alice_private_input_path: "/home/david/Desktop/spdz/Player-Data/Input-P0-0"
 bob_private_input_path: "/home/david/Desktop/spdz/Player-Data/Input-P1-0"
 path_to_top_of_mpspdz: "/home/david/Desktop/spdz"
 create_data: "False"